apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
      # Magento Application Container
      - name: magento
        image: praveenps18/magento-app:v1.0
        ports:
          - containerPort: 8080
        env:
          # Database variables. The host is now localhost because the proxy is a sidecar.
          - name: DB_HOST
            value: "127.0.0.1" 
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "magento_db"
          - name: DB_USER
            value: "myuser"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: magento-db-secret
                key: password
          # OpenSearch variables
          - name: OPENSEARCH_HOST
            value: "opensearch-service"
          - name: OPENSEARCH_PORT
            value: "9200"
      
      # Cloud SQL Proxy Sidecar Container
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        command:
          - "/cloud-sql-proxy"
          - "--port=3306"
          - "my-infracreation:us-central1:magento"
      imagePullSecrets:
      - name: regcred
