apiVersion: v1
kind: Service
metadata:
  name: magento-service
  labels:
    app: magento
spec:
  type: NodePort
  selector:
    app: magento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
