apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
      - name: magento
        image: praveenps18/magento-app:v5
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "magento_db"
          - name: DB_USER
            value: "myuser"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: magento-db-secret
                key: password
      
      # Cloud SQL Proxy with service account key
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        command:
          - "/cloud-sql-proxy"
          - "--structured-logs"
          - "--port=3306"
          - "--address=127.0.0.1"
          - "--credentials-file=/secrets/cloudsql/service-account.json"
          - "my-infracreation:us-central1:magento"
        volumeMounts:
          - name: cloudsql-service-account
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-service-account
          secret:
            secretName: cloudsql-service-account
