apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    name: http
  - port: 9600
    name: transport
  clusterIP: None
  selector:
    app: opensearch
